Basic setup
trthingnes/scaffolding-vr pull request #2
Opened 2024-03-06 09:21 UTC by thadshap

Removed not used objects and scripts from scene and added blink effect script

2024-03-06 09:22 UTC, trthingnes approved these changes

2024-03-06 09:24 UTC, trthingnes requested changes
We should add scaffolding kit to gitignore

2024-03-10 17:18 UTC, thadshap commented
Changed the path of the scaffolding kit in .gitignore and changed the names of the scaffolding parts

2024-03-13 08:46 UTC, trthingnes approved these changes

2024-03-13 08:51 UTC, trthingnes approved these changes

2024-03-13 08:52 UTC, merged